// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoz1C3_BqB0w3fYlxF6JgWLHy1T7wHlA4',
    appId: '1:38785005400:web:54d4d9d0cf1198128f972d',
    messagingSenderId: '38785005400',
    projectId: 'emergency-allergy-app',
    authDomain: 'emergency-allergy-app.firebaseapp.com',
    storageBucket: 'emergency-allergy-app.appspot.com',
    measurementId: 'G-E6FV4J4LVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBRjPYNe1zaKU_MLxp9azoYg0JK6WrSiA',
    appId: '1:38785005400:android:0753073e150c1b538f972d',
    messagingSenderId: '38785005400',
    projectId: 'emergency-allergy-app',
    storageBucket: 'emergency-allergy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVx4Tqa4Yb1ID5P5tFxqGlHB8JpiUgvhg',
    appId: '1:38785005400:ios:eca65257dbc3a21b8f972d',
    messagingSenderId: '38785005400',
    projectId: 'emergency-allergy-app',
    storageBucket: 'emergency-allergy-app.appspot.com',
    iosBundleId: 'com.example.emergencyAllergyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVx4Tqa4Yb1ID5P5tFxqGlHB8JpiUgvhg',
    appId: '1:38785005400:ios:eca65257dbc3a21b8f972d',
    messagingSenderId: '38785005400',
    projectId: 'emergency-allergy-app',
    storageBucket: 'emergency-allergy-app.appspot.com',
    iosBundleId: 'com.example.emergencyAllergyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoz1C3_BqB0w3fYlxF6JgWLHy1T7wHlA4',
    appId: '1:38785005400:web:6c58a23bdd032f348f972d',
    messagingSenderId: '38785005400',
    projectId: 'emergency-allergy-app',
    authDomain: 'emergency-allergy-app.firebaseapp.com',
    storageBucket: 'emergency-allergy-app.appspot.com',
    measurementId: 'G-XJY9W8R0XJ',
  );

}